### ISSUE TITLE
Comando “sugestao” não funciona

### ISSUE THREAD

**Issue by DQ318** [hell-ctrl/anny-bot#1]
Olá pessoal.

Estive testando o bot, devo dizer que é um ótimo trabalho feito por vocês.

Não sei se eu que não soube utilizar mas o comando sugestao não envia a mensagem privada para o “criador”, mesmo no original ou no código modificado para o meu celular, por exemplo.

Poderiam me auxiliar?

obrigado!

**Comment by hell-ctrl** [comment]
Eai, desculpa a demora pra responder, não entro muito aqui. Eu ajudo sim.

chama no WhatsApp: wa.me/559887583208
